version: '3.7'
services:
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sentryc_interview
    networks:
      - elastic

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - elastic

  app:
    container_name: seller
    image: seller
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
      - redis
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - elastic

networks:
  elastic:
    driver: bridge