spring:
  application:
    name: graphql-api
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/sentryc_interview
    hikari:
      poolName: Hikari
      auto-commit: false

  graphql:
    graphiql:
      enabled: true

  flyway:
    locations: classpath:db/migration

  data:
    redis:
      host: localhost
      port: 6379



